name: Build Release APK (Signed)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore
        shell: bash
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          ls -la keystore.jks

      - name: Give gradlew permission
        run: chmod +x AuryxBrowser/gradlew

      - name: Build SIGNED Release APK
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd AuryxBrowser
          ./gradlew --no-daemon --stacktrace clean assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: AuryxBrowser-release
          path: AuryxBrowser/app/build/outputs/apk/release/*.apk
